services:

  postgres_database:
    image: postgres:17.2
    container_name: postgres_cont
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ptest 
      POSTGRES_DB: general
    volumes:
      - users_database:/var/lib/postgresql/data
    networks:
      - composer_net
    expose:
      - 5432

  server:
    build: server/
    command: fastapi run ./server_handler.py
    depends_on:
      - postgres_database
    ports:
      - 8000:8000
    networks:
      - composer_net
      - virtual_external_net
      
  client:
    build: client/
    command: python ./client_request.py
    depends_on:
      - server
    networks:
      - composer_net
      - virtual_external_net
  
volumes:
  users_database:
    external: true

networks:
  composer_net:
  virtual_external_net:
    

