services:

  postgres_database:
    image: postgres:17.2
    container_name: postgres_cont
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ptest 
      POSTGRESS_DB: general
    volumes:
      - users_database:/var/lib/postgresql/data
    networks:
      - composer_net
    

  main_server:
    build: main_server/
    command: fastapi run ./server_handler.py
    depends_on:
      - postgres_database
    ports:
      - 8000:8000
    networks:
      - composer_net
      
  client:
    build: client/
    command: python ./client_request.py
    depends_on:
      - main_server
  
volumes:
  users_database:
    external: true

networks:
  composer_net:
    name: composer_main_network
    external: true

    

